---
- name: Playbook Control Lab
  hosts: all
  vars_files: vars.yml

  tasks:
    #Fail Fast Message
    - name: Show Failed System Requirements Message
      fail:
        msg: "The {{ inventory_hostname }} did not meet minimum reqs."
      when: >
        ansible_memtotal_mb < min_ram_mb or
        ansible_distribution != "RedHat"
    
    #Install all packages
    - name: Ensure required packages are present
      yum:
        name: "{{ packages }}"
        state: latest

    #Enable and start services
    - name: Start services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ services }}"
    
      #Block of config tasks
    - name: Config tasks
      block:
        - name: Ensure ssl certificate directory exists
          file:
            path: "{{ ssl_cert_dir }}"
            state: directory

        - name: Copy web config files to remote host
          copy: 
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
          loop: "{{ web_config_files }}"
          notify: restart web service
      
      rescue:
        - name: debug config tasks
          debug:
            msg: >
              One or more of the configuration
              changes failed, but the web service
              is still active.

      #Configure the firewall
    - name: Configure the firewall
      firewalld:
        service: "{{ item }}"
        immediate: true
        permanent: true
        state: enabled
      loop:
      - http
      - https
    
    #handlers
    - handlers:
      - name: restart web service
        service:
         name: "{{ web_service }}"
         state: restarted